services:
  mysql:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password --sql_mode=""
    restart: on-failure
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
  
  python:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app

  dataiku:
    image: dataiku/dss
    ports:
      - "10000:10000"
    volumes:
      - ./dataiku:/home/dataiku/dss
    environment:
      - DSS_PORT=10000
      - DSS_SECURITY_PUBLICAUTH_MODE=disabled
      - DSS_SECURITY_AUTHENTICATION_MODE=disabled

      
volumes:
  db:
